wx:
  appId: wx698220e7667a01e3
  appSecret: 882d28c93d94c8b7a5450fd0d45a052f
  urlBase: https://api.weixin.qq.com
  urlCode2Session: /sns/jscode2session

swagger2:
  title: api 文档 | 丢啦啦

spring:
  datasource:
      url: jdbc:mysql://47.93.187.44:3306/diulala
      username: dev
      password: 19961120