spring:
  profiles:
#    active: prod
    active: dev


  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

qiniu:
  accessKey: 8L5HuMHOhue9uekm4_IDtBjzc-a2TktcQqc4hliN
  secretKey: UZbUiGUGXavPqD87Gzhg3vFpEZtZujOUDP8-8UH5
  domain: http://p6tlx6vbg.bkt.clouddn.com
#  domain: http://urpimg.letec.top
  timeout: 900
