spring:
  application:
      name: URPSearchEngine
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/urp_search_engine
    username: root
    password: 19961120zheng
server:
  port: 8084
