spring:
  application:
      name: Diulala
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  redis:
    host: localhost
    port: 6379
server:
  port: 8084

spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/diulala?characterEncoding=utf-8&useUnicode=true
      username: admin
      password: admin

# 调试模式开关，调试模式下某些拦截器不会开启
debug:
  debug: true

